CREATE TABLE SALESREP
    AS (SELECT EMPLOYEE_ID AS REPID, FIRST_NAME AS FNAME, LAST_NAME AS LNAME, PHONE_NUMBER AS PHONE#, SALARY, COMMISSION_PCT AS COMISSION
       FROM EMPLOYEES
    WHERE DEPARTMENT_ID=80)


INSERT INTO CUST (CUST#,CUSTNAME, CITY,RATING, SALESREP#) 
     VALUES (201, 'ABCLTD.', 'MONTREAL', 'C', 201)
  


INSERT INTO CUST (CUST#,CUSTNAME, CITY,RATING, SALESREP#)
    VALUES (502, 'BLCK GIANT', 'OTTAWA', 'B', 202)


INSERT INTO CUST (CUST#,CUSTNAME, CITY,RATING, SALESREP#)
    VALUES (&CUST, &CUSTNAME, &CITY, &RATING, &SALESREP)


INSERT INTO CUST (CUST#,CUSTNAME, CITY,RATING, SALESREP#)
    VALUES (&CUST, &CUSTNAME, &CITY, &RATING, &SALESREP)


INSERT INTO CUST (CUST#,CUSTNAME, CITY,RATING, SALESREP#)
   VALUES (&CUST, &CUSTNAME, &CITY, &RATING, &SALESREP)


INSERT INTO CUST (CUST#,CUSTNAME, CITY,RATING, SALESREP#)
    VALUES (&CUST, &CUSTNAME, &CITY, &RATING, &SALESREP)


INSERT INTO CUST (CUST#,CUSTNAME, CITY,RATING, SALESREP#)
    VALUES (&CUST, &CUSTNAME, &CITY, &RATING, &SALESREP)



CREATE TABLE GOODCUST
    AS (SELECT CUST# AS CUSTID, CUSTNAME AS NAME, CITY AS LOCATION, SALESREP# AS REPID
        FROM CUST
        WHERE RATING = 'A' AND RATING = 'B')
                                                                                                             
SELECT *
    FROM GOODCUST


ALTER TABLE SALESREP
    ADD (JOBCODE VARCHAR2(12))

ALTER TABLE SALESREP
   MODIFY SALARY  NOT NULL
                                                                                                         


ALTER TABLE GOODCUST  MODIFY (LOCATION NULL)

SELECT LENGTH(CUSTNAME) FROM GOODCUST;

ALTER TABLE CUST
    MODIFY        (CUSTNAME VARCHAR2 (7));


ALTER TABLE SALESREP
    MODIFY REPID PRIMARY KEY


ALTER TABLE GOODCUST
   MODIFY CUSTID PRIMARY KEY

ALTER TABLE SALESREP
    ADD CONSTRAINT SALES_PHONE_UK UNIQUE(Phone#)

ALTER TABLE GOODCUST
    ADD CONSTRAINT GOOD_NAME_UK UNIQUE(NAME)
 
ALTER TABLE SALESREP
   ADD CONSTRAINT SALES_SALARY_CK CHECK (SALARY BETWEEN 6000 AND 12000)

ALTER TABLE SALESREP
   ADD CONSTRAINT SALES_COMMISIION_CK CHECK (COMISSION  <=0.5)

ALTER TABLE GOODCUST
    ADD CONSTRAINT GOODCUST_REPID_FK FOREIGN KEY (REPID) REFERENCES SALESREP (REPID)

select * from goodcust


UPDATE goodcust
SET RepId = NULL;


ALTER TABLE goodcust 
ADD CONSTRAINT goodcust_validate_fk FOREIGN KEY (RepId) REFERENCES salesrep(RepId);


ALTER TABLE goodcust
Disable CONSTRAINT goodcust_validate_fk;


UPDATE goodcust 
SET RepId = 202 
WHERE CUSTID = 502;


UPDATE goodcust 
SET RepId = 202 
WHERE CUSTID = 503;


UPDATE goodcust 
SET RepId = 102 
WHERE CUSTID = 701;


UPDATE goodcust 
SET RepId = 107 
WHERE CUSTID = 702;


ALTER TABLE goodcust
ADD CONSTRAINT goodcust_validate_fk FOREIGN KEY (RepId) REFERENCES salesrep(RepId);
              

ALTER TABLE salesrep
    DROP CONSTRAINT SALES_SALARY_CK CHECK;


ALTER TABLE salesrep
    ADD CONSTRAINT SALES_SALARY_CK CHECK(Salary BETWEEN 5000 AND 15000);

SELECT  constraint_name, constraint_type, search_condition, table_name
    FROM user_constraints
    WHERE UPPER(table_name) IN ('SALESREP', 'GOODCUST')
    ORDER BY 4,2;

                                                                                                         





